# Generated by Django 4.1.7 on 2024-01-21 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('sent_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('host_email', models.EmailField(blank=True, default='officail@utsavchatterjee.me', max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=datetime.datetime(2024, 1, 21, 14, 48, 10, 967192))),
            ],
        ),
    ]
